require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 40

Metrics/PerceivedComplexity:
    Max: 40

Style/AsciiComments:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
